/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary": "var(--color-on-primary)",
        "tertiary": "var(--color-tertiary)",
        "surface-bright": "var(--color-surface-bright)",
        "surface-container-low": "var(--color-surface-container-low)",
        "primary-container": "var(--color-primary-container)",
        "inverse-primary": "var(--color-inverse-primary)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "inverse-surface": "var(--color-inverse-surface)",
        "surface-variant": "var(--color-surface-variant)",
        "error-container": "var(--color-error-container)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "surface-container": "var(--color-surface-container)",
        "on-error-container": "var(--color-on-error-container)",
        "outline-variant": "var(--color-outline-variant)",
        "surface": "var(--color-surface)",
        "on-background": "var(--color-on-background)",
        "surface-container-high": "var(--color-surface-container-high)",
        "primary": "var(--color-primary)",
        "outline": "var(--color-outline)",
        "secondary": "var(--color-secondary)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "background": "var(--color-background)",
        "error": "var(--color-error)",
        "surface-tint": "var(--color-surface-tint)",
        "on-surface": "var(--color-on-surface)",
        "on-tertiary": "var(--color-on-tertiary)",
        "on-secondary": "var(--color-on-secondary)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "secondary-container": "var(--color-secondary-container)",
        "surface-dim": "var(--color-surface-dim)",
        "tertiary-container": "var(--color-tertiary-container)",
        "primary-fixed": "var(--color-primary-fixed)",
        "on-primary-container": "var(--color-on-primary-container)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "on-error": "var(--color-on-error)",
        // Standard theme variable mappings
        "surface-secondary": "var(--color-surface-secondary)",
        "border": "var(--color-border)",
        "primary-hover": "var(--color-primary-hover)",
        "text": "var(--color-text)",
        "text-secondary": "var(--color-text-secondary)",
        "placeholder-color": "var(--color-placeholder)",
        "danger": "var(--color-danger)",
        "success": "var(--color-success)",
        "warning": "var(--color-warning)"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline-sm": ["Manrope"],
        "body-sm": ["Inter"],
        "display-lg": ["Manrope"],
        "body-md": ["Inter"],
        "label-caps": ["Geist"],
        "body-lg": ["Inter"],
        "headline-md": ["Manrope"],
        "mono-sm": ["Geist"]
      },
      fontSize: {
        "headline-sm": ["1.5rem", { "lineHeight": "2rem", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-sm": ["0.875rem", { "lineHeight": "1.25rem", "letterSpacing": "0em", "fontWeight": "400" }],
        "display-lg": ["3rem", { "lineHeight": "3.5rem", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md": ["1rem", { "lineHeight": "1.5rem", "letterSpacing": "-0.01em", "fontWeight": "400" }],
        "label-caps": ["0.75rem", { "lineHeight": "1rem", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "body-lg": ["1.125rem", { "lineHeight": "1.75rem", "letterSpacing": "-0.01em", "fontWeight": "400" }],
        "headline-md": ["1.875rem", { "lineHeight": "2.375rem", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "mono-sm": ["0.8125rem", { "lineHeight": "1.125rem", "letterSpacing": "0em", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
